# This is a basic workflow to help you get started with Actions

name: cronjob

on:
  repository_dispatch:
    types: [pipedream]
  workflow_dispatch:
  schedule:
    # every sunday morning at 4:00
    - cron: "0 4 * * 0"

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Aggregate data
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: build
        run: npm ci && npm run build
      - name: Add & Commit
        uses: EndBug/add-and-commit@v4.4.0
        with:
          add: public/data
          author_name: roboter
          author_email: roboter@ff6347.email
          message: "Update via workflow"
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged

